### ISSUE TITLE
Cannot install any module via Marketplace (ps_mbo)

### ISSUE THREAD

**Issue by wapry90** [PrestaShopCorp/ps_mbo#721] opened 2024-02-09 16:11 UTC
Hello Team,

i'm facing an issue after upgrade from 1.7 to 8.0.0. The issue is related to Prestashop Marketplace and I cannot install any module. I receive the following error: "admin_token must be a string". Using Chrome Inspector, I can see that when I press install button, the following request goes in error (400 bad request) with the above message.
https://mbo-api.prestashop.com/api/shops/action.

I'm using latest version of ps_mbo and i already tried to uninstall/install the module.

Thanks for the support.

![error](https://github.com/PrestaShopCorp/ps_mbo/assets/159557152/2a97a418-5f61-4f27-ad35-25843984c0c7)

**Comment by intraordinaire** [comment] 2024-02-12 09:12
Hello @wapry90 ,

First of all, thanks for your feedback.

Some questions : 

- What is your mbo module version ?
- Is the shop update recent ?
- If yes, why stopping on a 8.0.0 ? 
- Are you on a dev env or a production one ?
- If it's ok for you, can you tell us your shop URL ?

My first guess here is the following :
We had several troubles on module actions (install, updates...) on PS version 8.0.0, and fixes were made on patch versions 8.0.1 & 8.0.2 (at least).
If it's possible for you, I'll suggest you to try to update to a newer PS version, the 8.0.5, or even better, the 8.1.3.

Anyway, we'll try to reproduce this.
And don't hesitate to give all other info you may have related to this issue.
Thanks 🙏

**Comment by intraordinaire** [comment] 2024-02-12 10:02
Just tested it on a fresh 8.0.0 with the 4.9.0 module, worked for me. I managed to install modules.

> 
> I'm using latest version of ps_mbo and i already tried to uninstall/install the module.
> 

Have you tried to remove the folder from the file system and re-upload the last zip from [github](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.9.0) ?

**Comment by wapry90** [comment] 2024-02-12 15:41
Hello,

yes, I'm using latest version of the module (4.9.0) and I already tied to uninstall -> delete folder -> upload zip module.   I guess the problem is related on something occurred during Prestashop upgrade.   Now I have resolved installing the module manually instead of automatically via Marketplace.
I'm planning to upgrade Prestashop to latest version hoping to fix the issue.

**Comment by intraordinaire** [comment] 2024-02-12 15:56
Ok, glad to hear you're planning this.
Strange bug, never seen this error before. So indeed, I think there's a problem elsewhere that's causing this behavior.
We can have a look and try to force this scenario to better handle it.

**Comment by intraordinaire** [comment] 2024-02-23 13:57
I'll close this issue since it seems not to be directly related to the module.

Don't hesitate to reopen an issue if you have a problem.

Thanks !

**Closed by intraordinaire** 2024-02-23 13:57 UTC
