### ISSUE TITLE
setDefaultParams() must be of the type string

### ISSUE THREAD

**Issue by afxgroup** [PrestaShopCorp/ps_mbo#754] opened 2024-04-12 15:58 UTC
I've updated ps_mbo to the latest version available for prestashop 1.7.8 and now the admin panel doesn't work anymore.
I get this error:

```PrestaShop\Module\Mbo\Addons\ApiClient::setDefaultParams() must be of the type string, null given, called in appProdProjectContainer.php on line 3494```

And the only way to enter in backoffice is to delete the module from db, delete the cache and force AdminModulesCatalog as controller in marketplace.
Any hint?

**Comment by intraordinaire** [comment] 2024-04-15 07:51
Hello @afxgroup,

Thanks for your feedback.

The class `PrestaShop\Module\Mbo\Addons\ApiClient` is instantiated through Symfony services, and maybe something is missing or is not well initialized before the call.

https://github.com/PrestaShopCorp/ps_mbo/blob/11daf498405de04f3b9ff145bb0fb673f1c86e40/config/services/addons.yml#L7

Some questions : 
 - PHP Version ?
 - Have you tried to clear the cache after installing the module ? 
    - There's some issue on cache clear, and it may cause trouble after module installation/upgrade.

In the meantime, we try to reproduce it.

**Comment by afxgroup** [comment] 2024-04-15 13:04
Yes, i've cleared the cache several times of course

PHP version 7.4.33 on nginx

This is my addons.yml:

```services:
  _defaults:
    public: true

  # Addons API Client
  mbo.addons.client.api:
    class: PrestaShop\Module\Mbo\Addons\ApiClient
    arguments:
      - "@mbo.addons.client.http"
    calls:
      - method: setDefaultParams
        arguments:
          - "@=service('translator').getLocale()"
          - "@=service('prestashop.adapter.data_provider.country').getIsoCodebyId()"
          - "@=service('prestashop.adapter.legacy.configuration').get('_PS_BASE_URL_')"
          - "@=service('prestashop.core.foundation.version').getSemVersion()"```

It seems upgraded from version 2.33 (if I remember correctly) to 3.1.1

**Comment by intraordinaire** [comment] 2024-04-23 12:59
@afxgroup 
We tried to reproduce it, but with no success :(

https://github.com/PrestaShopCorp/ps_mbo/assets/1721887/3641e57d-7729-41a0-95dc-7c468dd7c02b

Can you try to dump somewhere the values of the needed arguments ?

**Comment by intraordinaire** [comment] 2024-05-20 09:42
As we don't have any news, I close the issue.

Feel free to reopen it if needed, or open another if you find something else.

Thanks !

**Closed by intraordinaire** 2024-05-20 09:42 UTC

**Comment by intraordinaire** [comment] 2024-08-07 15:02
Hello @afxgroup 

Very long time ago, you opened this bug, and we unfortunately did not find a solution.

But today, we found the root cause.

Your user in back-office (table `ps_employee`) may have a value in `id_lang` that was not present in the table `ps_lang`.
So the default param `@=service('translator').getLocale()` was null.

Some other features in the BO should not have worked as expected in this case (maybe silent errors, less visible).

**Comment by afxgroup** [comment] 2024-08-07 15:35
Thanks for reply
i've checked the languages and the problem was in a language no more in DB
However i get this error now on **Marketplace:**

`Oh no.. something went wrong
There has been a problem on our side. Refresh your page and if the problem persists, try again later.`

While: **Modules in the spotlight]** Has no problem

**Comment by intraordinaire** [comment] 2024-08-08 07:03
@afxgroup 

You can try to reset the module, maybe, the language problem causes another problem on the installation process.

**Comment by afxgroup** [comment] 2024-08-08 07:28
That did the trick.
Thank you

**Comment by intraordinaire** [comment] 2024-08-08 07:33
Glad we could finally help you!
Thank you for your patience 🙏
