### ISSUE TITLE
Modules load but do not display

### ISSUE THREAD

**Issue by ArkaKnight** [PrestaShopCorp/ps_mbo#276] opened 2022-09-23 16:01 UTC
When I try to display the catalog of modules in the backoffice (ps_mbo) it does not work.

PrestaShop : 1.7.8.7
ps_mob : 2.0.2

Do you have an idea ?

Thank you

![Screenshot1](https://user-images.githubusercontent.com/71455355/192001572-6220a795-422b-404a-8780-ea043a5985e2.png)

[video.webm](https://user-images.githubusercontent.com/71455355/192003413-e369f691-7982-4651-89e6-2533eb591294.webm)

**Comment by intraordinaire** [comment] 2022-11-28 08:20
Hello @ArkaKnight 
Sorry for the delay, do you still have the problem ?

I can't reproduce on a local or online machine ?
Maybe this was an API problem (API which retrieve the modules list)

Thanks

**Comment by intraordinaire** [comment] 2023-01-02 09:27
I close this issue.
If you still have the problem, please give us more details in order to let us investigate.

Thanks.

**Closed by intraordinaire** 2023-01-02 09:27 UTC
